# Generated by Django 2.2.9 on 2022-11-13 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221106_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={
                'verbose_name': 'Сообщество',
                'verbose_name_plural': 'Сообщества',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={
                'ordering': ['-pub_date'],
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
    ]
